package com.lotofacil.padraoperimetro;
import android.app.*; import android.os.*; import android.content.*; import android.graphics.*; import android.graphics.pdf.PdfDocument; import android.net.Uri; import android.provider.MediaStore; import android.view.*; import android.widget.*;
import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.regex.*;

public class MainActivity extends Activity {
 static final int PICK=7; static final Set<Integer> PR=new HashSet<>(Arrays.asList(2,3,5,7,11,13,17,19,23)), FB=new HashSet<>(Arrays.asList(1,2,3,5,8,13,21)), MI=new HashSet<>(Arrays.asList(7,8,9,12,13,14,17,18,19)), CR=new HashSet<>(Arrays.asList(3,8,11,12,13,14,15,18,23));
 ArrayList<int[]> cs=new ArrayList<>(); TextView st,out; ProgressBar bar; Button load,go,pdf; int[] last,game,fail,fr,fe; Profile bestP; int pred;
 public void onCreate(Bundle b){super.onCreate(b); ui();}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextSize(17);return b;}
 void ui(){ScrollView sv=new ScrollView(this);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(22,22,22,35);sv.addView(x);
 TextView h=new TextView(this);h.setText("🍀  LOTOFÁCIL V4\nPADRÃO + PERÍMETRO");h.setTextColor(Color.WHITE);h.setTextSize(25);h.setGravity(17);h.setPadding(8,24,8,24);h.setBackgroundColor(Color.rgb(106,27,154));x.addView(h);
 TextView d=new TextView(this);d.setText("\nEstuda histórico, perímetro, repetidas, soma, linhas, colunas, primos, Fibonacci, miolo, cruz e moldura.\n");d.setTextSize(15);x.addView(d);
 load=bt("1. CARREGAR RESULTADOS TXT/CSV");go=bt("2. ESTUDAR E GERAR JOGO");pdf=bt("3. GERAR PDF");go.setEnabled(false);pdf.setEnabled(false);x.addView(load);x.addView(go);x.addView(pdf);
 bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);x.addView(bar,new LinearLayout.LayoutParams(-1,45));st=new TextView(this);st.setText("\nAguardando base...");x.addView(st);out=new TextView(this);out.setTextSize(16);out.setPadding(0,15,0,25);x.addView(out);
 load.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);});go.setOnClickListener(v->run());pdf.setOnClickListener(v->savePdf());setContentView(sv);}
 protected void onActivityResult(int q,int r,Intent d){super.onActivityResult(q,r,d);if(q==PICK&&r==RESULT_OK&&d!=null)try{read(d.getData());st.setText("Base carregada: "+cs.size()+" concursos\nÚltimo: "+fmt(last));go.setEnabled(true);}catch(Exception e){st.setText("Erro: "+e.getMessage());}}
 void read(Uri u)throws Exception{cs.clear();BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u),StandardCharsets.UTF_8));Pattern p=Pattern.compile("\\d+");String l;while((l=br.readLine())!=null){Matcher m=p.matcher(l);ArrayList<Integer>a=new ArrayList<>();while(m.find()){int n=Integer.parseInt(m.group());if(n>=1&&n<=25)a.add(n);}if(a.size()>=15){int[]z=new int[15];Set<Integer>s=new HashSet<>();for(int i=0;i<15;i++){z[i]=a.get(a.size()-15+i);s.add(z[i]);}if(s.size()==15){Arrays.sort(z);if(cs.isEmpty()||!Arrays.equals(cs.get(cs.size()-1),z))cs.add(z);}}}br.close();if(cs.size()<100)throw new Exception("Base histórica insuficiente.");last=cs.get(cs.size()-1);}
 void run(){go.setEnabled(false);load.setEnabled(false);bar.setProgress(0);st.setText("Estudando padrões históricos...");new Thread(()->{try{engine();runOnUiThread(()->{bar.setProgress(100);st.setText("CONCLUÍDO - jogo dentro do padrão.");out.setText(report());go.setEnabled(true);load.setEnabled(true);pdf.setEnabled(true);});}catch(Exception e){runOnUiThread(()->{st.setText("Erro: "+e.getMessage());go.setEnabled(true);load.setEnabled(true);});}}).start();}
 static class Profile{int soma,par,pri,fib,mi,cr,mold,seq,rep;int[] li,co;}
 Profile prof(int[]g,int[]ant){Set<Integer>s=set(g),a=set(ant);Profile p=new Profile();for(int n:g){p.soma+=n;if(n%2==0)p.par++;if(PR.contains(n))p.pri++;if(FB.contains(n))p.fib++;if(MI.contains(n))p.mi++;if(CR.contains(n))p.cr++;}p.mold=15-p.mi;p.rep=inter(s,a);p.li=new int[5];p.co=new int[5];for(int n:g){p.li[(n-1)/5]++;p.co[(n-1)%5]++;}int cur=1;p.seq=1;for(int i=1;i<g.length;i++){cur=g[i]==g[i-1]+1?cur+1:1;p.seq=Math.max(p.seq,cur);}return p;}
 static Set<Integer>set(int[]a){Set<Integer>s=new HashSet<>();for(int n:a)s.add(n);return s;} static int inter(Set<Integer>a,Set<Integer>b){int n=0;for(int x:a)if(b.contains(x))n++;return n;}
 double q(ArrayList<Integer>a,double q){Collections.sort(a);double p=(a.size()-1)*q;int lo=(int)Math.floor(p),hi=(int)Math.ceil(p);return lo==hi?a.get(lo):a.get(lo)*(hi-p)+a.get(hi)*(p-lo);}
 void engine(){ArrayList<Profile> ps=new ArrayList<>();ArrayList<Integer> reps=new ArrayList<>();for(int i=0;i<cs.size();i++){Profile p=prof(cs.get(i),i>0?cs.get(i-1):cs.get(i));ps.add(p);if(i>0)reps.add(p.rep);}runOnUiThread(()->bar.setProgress(15));
 // exact V4-style perimeter: recent signature, fallback + recent/history weighting
 int[] sig={reps.get(reps.size()-3),reps.get(reps.size()-2),reps.get(reps.size()-1)};Counter rc=new Counter();for(int i=3;i<reps.size();i++)if(reps.get(i-3)==sig[0]&&reps.get(i-2)==sig[1]&&reps.get(i-1)==sig[2])rc.add(reps.get(i),8);if(rc.total()<5){rc=new Counter();for(int i=2;i<reps.size();i++)if(reps.get(i-2)==sig[1]&&reps.get(i-1)==sig[2])rc.add(reps.get(i),8);}for(int i=Math.max(0,reps.size()-30);i<reps.size();i++)rc.add(reps.get(i),2);Counter all=new Counter();for(int r:reps)all.add(r,1);for(int r=0;r<=15;r++)rc.add(r,(int)Math.round(all.get(r)*20.0/reps.size()));pred=9;double bs=-1;for(int r=8;r<=11;r++){double v=rc.get(r);if(v>bs){bs=v;pred=r;}}
 final int qr=15-pred,qe=10-qr;Set<Integer>ls=set(last);ArrayList<Integer>esp=new ArrayList<>();for(int n=1;n<=25;n++)if(!ls.contains(n))esp.add(n);
 runOnUiThread(()->{bar.setProgress(30);st.setText("Perímetro prevê "+pred+" repetidas. Gerando candidatos...");});
 ArrayList<Cand> rr=groups(last,qr,true), ee=groups(toArray(esp),qe,false);runOnUiThread(()->bar.setProgress(65));
 // historical percentile arrays
 Stats S=new Stats(ps);
 double best=-1e99;Cand br=null,be=null;Profile bp=null;int[]bg=null,bf=null;int tested=0,valid=0;
 for(Cand a:rr)for(Cand b:ee){tested++;int[]f=join(a.c,b.c);Arrays.sort(f);Set<Integer>fs=set(f);int[]g=new int[15];int k=0;for(int n=1;n<=25;n++)if(!fs.contains(n))g[k++]=n;Profile p=prof(g,last);if(!S.ok(p)||p.rep<8||p.rep>11)continue;valid++;double sp=S.score(p,pred),sf=a.s+b.s,total=sp+sf*.08;if(total>best){best=total;br=a;be=b;bp=p;bg=g;bf=f;}}
 if(bg==null)throw new RuntimeException("Nenhum jogo passou pelo padrão.");fr=br.c;fe=be.c;game=bg;fail=bf;bestP=bp;runOnUiThread(()->bar.setProgress(95));}
 static class Counter{int[]c=new int[16];void add(int x,int v){if(x>=0&&x<c.length)c[x]+=v;}int get(int x){return x>=0&&x<c.length?c[x]:0;}int total(){int s=0;for(int x:c)s+=x;return s;}}
 static class Cand{double s;int[]c;Cand(double s,int[]c){this.s=s;this.c=c;}}
 ArrayList<Cand> groups(int[]a,int k,boolean fromResult){ArrayList<Cand>r=new ArrayList<>();comb(a,k,0,new int[k],0,r,fromResult);r.sort((x,y)->Double.compare(y.s,x.s));return new ArrayList<>(r.subList(0,Math.min(140,r.size())));}
 void comb(int[]a,int k,int at,int[]buf,int d,ArrayList<Cand>r,boolean side){if(d==k){int[]c=buf.clone();double s=0;for(int n:c)s+=ind(n,side);int joint=0;for(int i=0;i<cs.size()-1;i++){Set<Integer>nx=set(cs.get(i+1));int f=0;for(int n:c)if(!nx.contains(n))f++;joint+=f==k?5:f==k-1?2:0;}r.add(new Cand(s+joint,c));return;}for(int i=at;i<=a.length-(k-d);i++){buf[d]=a[i];comb(a,k,i+1,buf,d+1,r,side);}}
 double ind(int d,boolean side){int tot=0,ev=0;for(int i=0;i<cs.size()-1;i++){Set<Integer>a=set(cs.get(i)),b=set(cs.get(i+1));if(side){if(a.contains(d)){tot++;if(!b.contains(d))ev++;}}else if(!a.contains(d)){tot++;if(!b.contains(d))ev++;}}double base=ev*100.0/Math.max(1,tot),rec=0;double[]w={1,1.5,2};int st=Math.max(0,cs.size()-4),j=3-(cs.size()-1-st);for(int i=st;i<cs.size()-1;i++,j++){Set<Integer>a=set(cs.get(i)),b=set(cs.get(i+1));boolean e=side?(a.contains(d)&&!b.contains(d)):(!a.contains(d)&&!b.contains(d));if(e)rec+=w[j];}return base+rec*12;}
 static int[]toArray(ArrayList<Integer>a){int[]x=new int[a.size()];for(int i=0;i<x.length;i++)x[i]=a.get(i);return x;} static int[]join(int[]a,int[]b){int[]x=Arrays.copyOf(a,a.length+b.length);System.arraycopy(b,0,x,a.length,b.length);return x;}
 class Stats{double[]lo=new double[8],hi=new double[8],med=new double[8],p10=new double[8],p90=new double[8];double[][]llo=new double[2][5],lhi=new double[2][5],lmed=new double[2][5];Stats(ArrayList<Profile>p){for(int k=0;k<8;k++){ArrayList<Integer>a=new ArrayList<>();for(Profile x:p)a.add(val(x,k));lo[k]=q(a,.02);hi[k]=q(a,.98);med[k]=q(a,.5);p10[k]=q(a,.1);p90[k]=q(a,.9);}for(int t=0;t<2;t++)for(int j=0;j<5;j++){ArrayList<Integer>a=new ArrayList<>();for(Profile x:p)a.add(t==0?x.li[j]:x.co[j]);llo[t][j]=q(a,.02);lhi[t][j]=q(a,.98);lmed[t][j]=q(a,.5);}}int val(Profile p,int k){return new int[]{p.soma,p.par,p.pri,p.fib,p.mi,p.cr,p.mold,p.seq}[k];}boolean ok(Profile p){for(int k=0;k<8;k++){int v=val(p,k);if(v<lo[k]||v>hi[k])return false;}for(int j=0;j<5;j++)if(p.li[j]<llo[0][j]||p.li[j]>lhi[0][j]||p.co[j]<llo[1][j]||p.co[j]>lhi[1][j])return false;return true;}double score(Profile p,int pr){double s=0;for(int k=0;k<8;k++){double spread=Math.max(1,p90[k]-p10[k]);s-=Math.abs(val(p,k)-med[k])/spread*12;if(val(p,k)>=p10[k]&&val(p,k)<=p90[k])s+=6;}for(int j=0;j<5;j++){s-=Math.abs(p.li[j]-lmed[0][j])*5;s-=Math.abs(p.co[j]-lmed[1][j])*5;}s-=Math.abs(p.rep-pr)*30;return s;}}
 String report(){return "FALHAS DO RESULTADO ("+fr.length+"): "+fmt(fr)+"\nFALHAS DO ESPELHO ("+fe.length+"): "+fmt(fe)+"\n\n10 FALHAS: "+fmt(fail)+"\n\nJOGO FINAL - 15:\n"+fmt(game)+"\n\nCLASSIFICAÇÃO\nRepetidas: "+bestP.rep+"\nSoma: "+bestP.soma+"\nPares: "+bestP.par+"\nPrimos: "+bestP.pri+"\nFibonacci: "+bestP.fib+"\nMiolo: "+bestP.mi+"\nCruz: "+bestP.cr+"\nMoldura/Borda: "+bestP.mold+"\nMaior sequência: "+bestP.seq+"\nLinhas: "+Arrays.toString(bestP.li)+"\nColunas: "+Arrays.toString(bestP.co);}
 String fmt(int[]a){StringBuilder s=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)s.append(" ");s.append(String.format(Locale.US,"%02d",a[i]));}return s.toString();}
 void savePdf(){try{PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=p.getCanvas();Paint x=new Paint(1);x.setTypeface(Typeface.DEFAULT_BOLD);x.setColor(Color.rgb(106,27,154));x.setTextSize(23);c.drawText("LOTOFÁCIL V4 - PADRÃO + PERÍMETRO",35,50,x);x.setTextSize(15);x.setColor(Color.BLACK);c.drawText("JOGO FINAL - 15",35,95,x);x.setColor(Color.rgb(46,125,50));x.setTextSize(21);c.drawText(fmt(game),35,130,x);x.setColor(Color.BLACK);x.setTextSize(13);c.drawText("10 falhas: "+fmt(fail),35,175,x);c.drawText("Repetidas: "+bestP.rep+"   Soma: "+bestP.soma+"   Pares: "+bestP.par+"   Primos: "+bestP.pri,35,210,x);c.drawText("Fibonacci: "+bestP.fib+"   Miolo: "+bestP.mi+"   Cruz: "+bestP.cr+"   Moldura: "+bestP.mold,35,235,x);c.drawText("Linhas: "+Arrays.toString(bestP.li),35,260,x);c.drawText("Colunas: "+Arrays.toString(bestP.co),35,285,x);d.finishPage(p);String n="LOTOFACIL_V4_PADRAO_PERIMETRO.pdf";ContentValues cv=new ContentValues();cv.put(MediaStore.Downloads.DISPLAY_NAME,n);cv.put(MediaStore.Downloads.MIME_TYPE,"application/pdf");cv.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv);OutputStream o=getContentResolver().openOutputStream(u);d.writeTo(o);o.close();d.close();Toast.makeText(this,"PDF salvo em Download/"+n,Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Erro PDF: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}